#!/usr/bin/env python3

"""Run zig code through formatter, erroring out if something gets"""

import subprocess
import sys


def error(*args, **kwargs) -> None:
    print(*args, **kwargs, file=sys.stderr)


def main() -> int:
    _ = sys.argv.pop(0)  # executable (this file)

    # TODO(elpekenin): is this even posible?
    if len(sys.argv) == 0:
        return 0

    command = ["zig", "fmt", *sys.argv]
    ret = subprocess.run(
        command,
        capture_output=True,
    )

    if ret.stdout:
        error("Files changed")
        error("-------------")
        error(ret.stdout.decode())
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
